### ISSUE TITLE
Crashed when increase the AFC_NUM_FRAMES

### ISSUE THREAD

**Issue by fanday** [nihospr01/OpenSpeechPlatform-UCSD#1]
Hi,
    OSP is pretty good and it works well.But when  increase the AFC_NUM_FRAMES it will crash the application.AFC_NUM_FRAMES is 7 by default.So increase AFC frames number will eliminated the long range acoustic feedback?thanks in advance.

**Comment by dhimnsen** [comment]
Hi sorry for the late reply we have been hard at work updating the code base to make it more modular. We have completely revamped our code so take a look at it now. I believe the algorithm team hard coded this in at one point, however, the new set of code is a bit more modular and so it should be easier to do what you are asking. Let me know if it works or else I can get one of the algorithm developers to take a look at it and get back to you.

**Comment by DrDareDevel** [comment]
No longer valid
