### ISSUE TITLE
No audio.

### ISSUE THREAD

**Issue by JEEaton001** [nihospr01/OpenSpeechPlatform-UCSD#3]
I am running 2018C on a linux virtual machine. I have everything installed but when I run osp in the terminal it pops up with:

![image](https://user-images.githubusercontent.com/37002668/58595112-d24dd980-822c-11e9-9ab7-8a5329dd1e9f.png)

the program is running and i can change parameters but i do not have any audio output.

I have verified alsa's install. and have checked that I am receiving sound from the virtual machine. and that the sound card is being recognized but i am still not getting sound. 

I am wondering if you have any ideas?

**Comment by dhimnsen** [comment]
Hi,

So with OSP on Ubuntu Port Audio chooses the default devices which may not be the ones that you want. Therefore, I would suggest running "pa_devs" and this will list all of the devices. Next, search through the list and find your input device and your output device (input and output devices may be the same device). At this point run OSP through the following command "osp --input_device x --output_device y". Where x and y are the device numbers for your input and output. Please let me know if this solved your issue.

![image](https://user-images.githubusercontent.com/11894636/58598949-265bbc80-8233-11e9-828b-7368071955b0.png)

**Comment by JEEaton001** [comment]
Thank you for the quick response.

Sadly this did not work. Ive tried the inputs and outputs I want, and every
other combination possible. I am not able to get sound out of osp or ews.
And most of the time I am getting sound from other Linux sources. I have
reinstalled osp and that did not change anything. I am wondering if you
guys have a list of troubleshooting tips I can run through. Or an example
of how to use the system besides the provided pdfs to see if I am doing
something wrong.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by JEEaton001** [comment]
I have also tried installing this on an embedded linux device. And
everything has seemed to install but the osp start command. I checked
/usr/local/bin and it installed ews but not osp. And I am wondering what
files I would need to run to install that command to test the system.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DrDareDevel** [comment]
I haven't anything for over a year on this issue, closing the ticket
